In [1]:
import tensorflow as tf
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization
from tensorflow.keras.applications.vgg19 import VGG19
from tensorflow.keras.preprocessing import image
import PIL
from PIL import Image
import numpy as np
from numpy import asarray
from sklearn.model_selection import train_test_split
import glob

In [2]:
import zipfile
zip_ref = zipfile.ZipFile('flickr8k.zip', "r")
zip_ref.extractall()
zip_ref.close()

In [3]:
output_file = open('captions.txt',mode='r')
lines = output_file.readlines()
lines.pop(0)
lines = np.asarray(lines)
l = len(lines)
l = int(l/5)
print(l)
lines.shape = (l,5)
print(lines[0])
X = np.empty((l,224,224,3))
Y = np.empty((l,35,5))
i = 0

8091
['1000268201_693b08cb0e.jpg,A child in a pink dress is climbing up a set of stairs in an entry way .\n'
 '1000268201_693b08cb0e.jpg,A girl going into a wooden building .\n'
 '1000268201_693b08cb0e.jpg,A little girl climbing into a wooden playhouse .\n'
 '1000268201_693b08cb0e.jpg,A little girl climbing the stairs to her playhouse .\n'
 '1000268201_693b08cb0e.jpg,A little girl in a pink dress going into a wooden cabin .\n']


In [4]:
for images in glob.glob('./Images/*'):
  image = Image.open(images)
  x_center = image.size[0]
  y_center = image.size[1]
  left = x_center - 112
  right = x_center + 112
  upper = y_center - 112
  lower = y_center + 112
  image = image.crop((left,upper,right,lower))
  data = asarray(image)
  X[i, :, :, :] = data
  i+=1

In [5]:
max_vocab_length = 10000 # max number of words to have in our vocabulary
max_length = 35 # max length our sentence will be
text_vectorizer = TextVectorization(max_tokens=max_vocab_length,
                                    standardize="lower_and_strip_punctuation",
                                    split="whitespace",
                                    output_mode="int",
                                    output_sequence_length=max_length,
                                    )

In [6]:
X_train, X_test, sent_train, sent_test = train_test_split(X, lines, test_size=0.1235)

In [7]:
flatten_sent_train = sent_train.flatten()
l_train = sent_train.shape[0]
print(sent_train.shape,flatten_sent_train.shape)
text_vectorizer.adapt(flatten_sent_train)

(7091, 5) (35455,)


In [8]:
print(sent_test)
Y_train = text_vectorizer(flatten_sent_train)
Y_train

[['3343197133_9256848fa9.jpg,A biker gets high in the air against a skyline .\n'
  '3343197133_9256848fa9.jpg,A boy wearing a white helmet jumping on his bike .\n'
  '3343197133_9256848fa9.jpg,a cyclist is performing a jumping stunt in front of a city skyline .\n'
  '3343197133_9256848fa9.jpg,A man is in the air on his bicycle .\n'
  '3343197133_9256848fa9.jpg,"A person doing a bicycle jump , a skyline in the background ."\n']
 ['2353088412_5e5804c6f5.jpg,A black dog running with a stuffed bird in its mouth and another dog chasing it .\n'
  '2353088412_5e5804c6f5.jpg,A brown dig and black dog are playing with a stuffed toy .\n'
  '2353088412_5e5804c6f5.jpg,A brown dog with a toy duck in its mouth runs through snow while a black dog chases it\n'
  '2353088412_5e5804c6f5.jpg,Dog running with pet toy being chased by another dog .\n'
  '2353088412_5e5804c6f5.jpg,The brown dog is being chased by a black dog while holding a small toy in his mouth .\n']
 ['2400958566_4e09424046.jpg,A girl hik

<tf.Tensor: shape=(35455, 35), dtype=int64, numpy=
array([[9661, 1061,   10, ...,    0,    0,    0],
       [9661,   10,    6, ...,    0,    0,    0],
       [9661,   10,  102, ...,    0,    0,    0],
       ...,
       [4058,   53,  162, ...,    0,    0,    0],
       [4058,   53,  162, ...,    0,    0,    0],
       [4058,   53,  162, ...,    0,    0,    0]], dtype=int64)>

In [9]:
np.reshape(Y_train,(l_train,5,35))

array([[[9661, 1061,   10, ...,    0,    0,    0],
        [9661,   10,    6, ...,    0,    0,    0],
        [9661,   10,  102, ...,    0,    0,    0],
        [   1,   47,    5, ...,    0,    0,    0],
        [   1,   10,  102, ...,    0,    0,    0]],

       [[   1,   51,    8, ...,    0,    0,    0],
        [6185,   28,  152, ...,    0,    0,    0],
        [6185,   38,   12, ...,    0,    0,    0],
        [6185,   51,   12, ...,    0,    0,    0],
        [6185,  897,   28, ...,    0,    0,    0]],

       [[3319,   10,    3, ...,    0,    0,    0],
        [3319,   10,   74, ...,    0,    0,    0],
        [3319,   10,   19, ...,    0,    0,    0],
        [3319,   10,    9, ...,    0,    0,    0],
        [3319,   44,   74, ...,    0,    0,    0]],

       ...,

       [[   1,  333,   11, ...,    0,    0,    0],
        [   1, 1879,    1, ...,    0,    0,    0],
        [8926,  508,    3, ...,    0,    0,    0],
        [8926,   24,   84, ...,    0,    0,    0],
        [892

In [10]:
flatten_sent_test = sent_test.flatten()
l_test = sent_test.shape[0]
Y_test = text_vectorizer(flatten_sent_test)
np.reshape(Y_test,(l_test,5,35))

array([[[   1,  310,  395, ...,    0,    0,    0],
        [   1,   15,   19, ...,    0,    0,    0],
        [   1,  625,    6, ...,    0,    0,    0],
        [   1,   10,    6, ...,    0,    0,    0],
        [   1,   44,  134, ...,    0,    0,    0]],

       [[   1,   13,    8, ...,    0,    0,    0],
        [   1,   23,    1, ...,    0,    0,    0],
        [   1,   23,    8, ...,    0,    0,    0],
        [   1,   29,    9, ...,    0,    0,    0],
        [   1,   23,    8, ...,    0,    0,    0]],

       [[   1,   16,  632, ...,    0,    0,    0],
        [   1,  586,  136, ...,    0,    0,    0],
        [   1,  586,    9, ...,    0,    0,    0],
        [   1,   44, 1099, ...,    0,    0,    0],
        [   1,   17,    6, ...,    0,    0,    0]],

       ...,

       [[   1,  163,    5, ...,    0,    0,    0],
        [   1,   24,   14, ...,    0,    0,    0],
        [   1,   24, 1014, ...,    0,    0,    0],
        [   1,   24, 4746, ...,    0,    0,    0],
        [   

In [53]:
x_input = VGG19(weights='imagenet',include_top=False,input_shape=(224, 224, 3))
x = x_input.layers[-3].output
shape = x.shape
shape = tf.convert_to_tensor(shape)
print(shape)
# Reshape( (-1, nb_filters))(X)
# x3d = tf.reshape( x,(-1, shape[3] ) )
x3d = tf.reshape( x, [shape[0], shape[1] * shape[2], shape[3] ] )
# x = tf.keras.layers.Flatten()(x)
# x = tf.keras.layers.MaxPooling2D()(x)
print(x3d.shape)
x3d = tf.keras.layers.Dense(256, activation="relu")(x3d)
x3d = tf.keras.layers.Dropout(rate=0.3)(x3d)
x3d = tf.keras.layers.LSTM(512, dropout=0.3, return_sequences=True)(x3d)
x3d = tf.keras.layers.Dense(512, activation="relu")(x3d)
x3d = tf.keras.layers.Dropout(rate=0.3)(x3d)
x3d = tf.keras.Dropout(rate=0.3)(x3d)
y = tf.keras.Dense(175, activation="softmax")(x)
np.reshape(y,(5,35))
model = Model(inputs = [x_input], outputs = y)
model.compile(loss='mean_squared_error', optimizer='RMSProp', metrics=['accuracy'])
model.summary()
model.fit(X_train, Y_train, epochs=8, batch_size=64)
model.evaluate(X_test, Y_test)

ValueError: Cannot convert a partially known TensorShape to a Tensor: (None, 14, 14, 512)

In [ ]:
print(X_train.shape, Y_train.shape)